services:
  # Step 12
  # Make it so that the app starts and executable... docker compose up -d
  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/postgres?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  # =====================================================================
  # This is the first thing that will be run when the container starts
  # This is the first thing i should do before starting the app
  # docker compose up -d
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
